import type { Hotspot, ConflictZone, MilitaryBase, UnderseaCable, NuclearFacility, StrategicWaterway, APTGroup, EconomicCenter, Spaceport, CriticalMineralProject } from '@/types';

// Hotspot levels are NOT hardcoded - they are dynamically calculated based on news activity
// All hotspots start at 'low' and rise to 'elevated' or 'high' based on matching news items
// Escalation scores: 1=stable, 2=watchlist, 3=elevated, 4=high tension, 5=critical/active conflict
export const INTEL_HOTSPOTS: Hotspot[] = [
  {
    id: 'sahel',
    name: 'Sahel',
    subtext: 'Insurgency/Coups',
    lat: 14.0,
    lon: -1.0,
    location: 'Sahel Region (Mali, Burkina Faso, Niger)',
    keywords: ['burkina faso', 'mali', 'niger', 'sahel', 'junta', 'coup', 'wagner', 'africa corps'],
    agencies: ['Wagner', 'Junta Forces'],
    description: 'Region of instability, military coups, and Islamist insurgency. Russian influence growing.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['4 coups since 2020', 'French forces expelled', 'Wagner/Africa Corps expansion', 'ECOWAS sanctions'],
    history: {
      lastMajorEvent: 'Niger coup',
      lastMajorEventDate: '2023-07-26',
      precedentCount: 4,
      precedentDescription: '4 military coups in 3 years (Mali 2020/2021, Burkina Faso 2022, Niger 2023)',
      cyclicalRisk: 'Dry season offensives (Oct-May)',
    },
    whyItMatters: 'Russian influence expanding in former French sphere; jihadist groups gaining territory; migration pressure on Europe',
  },
  {
    id: 'haiti',
    name: 'Port-au-Prince',
    subtext: 'Haiti Crisis',
    lat: 18.5,
    lon: -72.3,
    location: 'Haiti, Caribbean',
    keywords: ['haiti', 'port-au-prince', 'gangs', 'kenya mission', 'barbecue'],
    agencies: ['UN', 'HNP', 'Kenya Police'],
    description: 'Gang violence, government collapse, international security mission.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'stable',
    escalationIndicators: ['Gangs control 80% of capital', 'PM resigned under pressure', 'Kenya-led mission deployed', 'Mass displacement'],
    history: {
      lastMajorEvent: 'PM Henry resignation',
      lastMajorEventDate: '2024-03-11',
      precedentCount: 3,
      precedentDescription: 'Repeated state collapse (2004 Aristide, 2021 Moïse assassination, 2024 gang takeover)',
      cyclicalRisk: 'Hurricane season vulnerability (Jun-Nov)',
    },
    whyItMatters: 'Humanitarian catastrophe at US doorstep; migration surge potential; test of African-led peacekeeping',
  },
  {
    id: 'horn_africa',
    name: 'Horn of Africa',
    subtext: 'Piracy/Conflict',
    lat: 10.0,
    lon: 49.0,
    location: 'Somalia, Ethiopia, Djibouti',
    keywords: ['somalia', 'piracy', 'al-shabaab', 'ethiopia', 'somaliland', 'red sea'],
    agencies: ['USAFRICOM', 'EUNAVFOR'],
    description: 'Resurgent piracy, Al-Shabaab activity, Ethiopia-Somaliland port dispute.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['Houthi attacks on shipping', 'Somali piracy resurgence', 'Ethiopia-Somaliland MoU dispute', 'Sudan civil war spillover'],
    history: {
      lastMajorEvent: 'Sudan war outbreak',
      lastMajorEventDate: '2023-04-15',
      precedentCount: 5,
      precedentDescription: 'Ethiopia-Eritrea war, Tigray war, Somali civil war, Sudan coups, piracy waves',
      cyclicalRisk: 'Monsoon affects naval operations (Jun-Sep)',
    },
    whyItMatters: 'Bab el-Mandeb chokepoint security; 12% of global trade at risk; Red Sea shipping rerouting',
  },
  {
    id: 'dc',
    name: 'DC',
    subtext: 'Pentagon Pizza Index',
    lat: 38.9,
    lon: -77.0,
    location: 'Washington D.C., USA',
    keywords: ['pentagon', 'white house', 'congress', 'cia', 'nsa', 'washington', 'biden', 'trump', 'house', 'senate', 'supreme court', 'vance', 'elon', 'us '],
    agencies: ['Pentagon', 'CIA', 'NSA', 'State Dept'],
    description: 'US government and military headquarters. Intelligence community center.',
    status: 'Monitoring',
  },
  {
    id: 'silicon_valley',
    name: 'Silicon Valley',
    subtext: 'Tech/AI Hub',
    lat: 37.4,
    lon: -122.1,
    location: 'California, USA',
    keywords: ['google', 'apple', 'meta', 'nvidia', 'openai', 'anthropic', 'silicon valley', 'san francisco', 'palo alto', 'tech layoffs', 'ai', 'artificial intelligence'],
    agencies: ['Big Tech', 'AI Labs', 'VC'],
    description: 'Global tech center. AI development hub. Major economic indicator.',
    status: 'Monitoring',
  },
  {
    id: 'wall_street',
    name: 'Wall Street',
    subtext: 'Financial Hub',
    lat: 40.7,
    lon: -74.0,
    location: 'New York City, USA',
    keywords: ['wall street', 'fed', 'federal reserve', 'nyse', 'nasdaq', 'dow', 'sp500', 'stock market', 'goldman', 'jpmorgan', 'blackrock'],
    agencies: ['Fed', 'SEC', 'NYSE'],
    description: 'Global financial center. Market movements. Fed policy.',
    status: 'Monitoring',
  },
  {
    id: 'houston',
    name: 'Houston',
    subtext: 'Energy/Space',
    lat: 29.76,
    lon: -95.37,
    location: 'Texas, USA',
    keywords: ['houston', 'nasa', 'spacex', 'oil', 'energy', 'texas', 'exxon', 'chevron', 'lng'],
    agencies: ['NASA', 'Energy Corps'],
    description: 'Energy sector HQ. NASA mission control. Space industry.',
    status: 'Monitoring',
  },
  {
    id: 'moscow',
    name: 'Moscow',
    subtext: 'Kremlin Activity',
    lat: 55.75,
    lon: 37.6,
    location: 'Russia',
    keywords: ['kremlin', 'putin', 'russia', 'fsb', 'moscow', 'russian'],
    agencies: ['Kremlin', 'FSB', 'GRU', 'SVR'],
    description: 'Russian Federation command center. Military operations hub.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'stable',
    escalationIndicators: ['Ukraine war ongoing', 'Mobilization potential', 'Nuclear rhetoric', 'Wagner aftermath'],
    history: {
      lastMajorEvent: 'Wagner mutiny',
      lastMajorEventDate: '2023-06-24',
      precedentCount: 2,
      precedentDescription: 'Crimea annexation 2014, Ukraine invasion 2022',
      cyclicalRisk: 'Victory Day (May 9) speeches, Putin addresses',
    },
    whyItMatters: 'Nuclear power at war; energy leverage over Europe; global order revisionism',
  },
  {
    id: 'beijing',
    name: 'Beijing',
    subtext: 'PLA/MSS Activity',
    lat: 39.9,
    lon: 116.4,
    location: 'China',
    keywords: ['beijing', 'xi', 'china', 'pla', 'ccp', 'chinese', 'jinping'],
    agencies: ['PLA', 'MSS', 'CCP Politburo'],
    description: 'Chinese Communist Party headquarters. PLA command center.',
    status: 'Monitoring',
    escalationScore: 3,
    escalationTrend: 'stable',
    escalationIndicators: ['Taiwan Strait exercises', 'South China Sea militarization', 'Tech decoupling', 'Xi third term'],
    history: {
      lastMajorEvent: 'Xi unprecedented third term',
      lastMajorEventDate: '2022-10-22',
      precedentCount: 3,
      precedentDescription: 'Tiananmen 1989, Hong Kong crackdown 2020, COVID lockdowns 2022',
      cyclicalRisk: 'Party Congress (every 5 years), Tiananmen anniversary (June 4)',
    },
    whyItMatters: 'Largest economy by PPP; primary US strategic competitor; Taiwan contingency risk',
  },
  {
    id: 'kyiv',
    name: 'Kyiv',
    subtext: 'Conflict Zone',
    lat: 50.45,
    lon: 30.5,
    location: 'Ukraine',
    keywords: ['kyiv', 'ukraine', 'zelensky', 'ukrainian', 'kiev'],
    agencies: ['Ukrainian Armed Forces', 'SBU'],
    description: 'Active conflict zone. NATO support operations.',
    status: 'Monitoring',
    escalationScore: 5,
    escalationTrend: 'stable',
    escalationIndicators: ['Active combat operations', 'Western weapons deliveries', 'Drone warfare escalation', 'Nuclear plant risks'],
    history: {
      lastMajorEvent: 'Russian full invasion',
      lastMajorEventDate: '2022-02-24',
      precedentCount: 2,
      precedentDescription: 'Crimea annexation 2014, Donbas war 2014-2022',
      cyclicalRisk: 'Spring/summer offensive season, Winter energy attacks',
    },
    whyItMatters: 'Largest European war since WWII; NATO Article 5 test; global food/energy security',
  },
  {
    id: 'taipei',
    name: 'Taipei',
    subtext: 'Strait Watch',
    lat: 25.03,
    lon: 121.5,
    location: 'Taiwan',
    keywords: ['taiwan', 'taipei', 'tsmc', 'strait', 'taiwanese'],
    agencies: ['ROC Military', 'TSMC'],
    description: 'Taiwan Strait tensions. Semiconductor supply chain.',
    status: 'Monitoring',
    escalationScore: 3,
    escalationTrend: 'stable',
    escalationIndicators: ['PLA exercises around Taiwan', 'US arms sales', 'TSMC Arizona fab', 'DPP governance'],
    history: {
      lastMajorEvent: 'Pelosi Taiwan visit',
      lastMajorEventDate: '2022-08-02',
      precedentCount: 3,
      precedentDescription: '1954-55 Strait Crisis, 1995-96 missile crisis, 2022 exercises',
      cyclicalRisk: 'US-Taiwan political visits, PRC National Day (Oct 1)',
    },
    whyItMatters: 'TSMC produces 90% of advanced chips; conflict would devastate global tech supply chains',
  },
  {
    id: 'tehran',
    name: 'Tehran',
    subtext: 'IRGC Activity',
    lat: 35.7,
    lon: 51.4,
    location: 'Iran',
    keywords: ['iran', 'tehran', 'irgc', 'khamenei', 'persian', 'iranian'],
    agencies: ['IRGC', 'Quds Force', 'MOIS'],
    description: 'Iranian nuclear program. Regional proxy operations.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['Near-weapons-grade enrichment', 'Proxy attacks on Israel', 'Houthi coordination', 'Succession uncertainty'],
    history: {
      lastMajorEvent: 'JCPOA collapse acceleration',
      lastMajorEventDate: '2023-01-01',
      precedentCount: 4,
      precedentDescription: 'Revolution 1979, Iran-Iraq War, JCPOA negotiations, Soleimani assassination',
      cyclicalRisk: 'Quds Day (annually), Khamenei health status',
    },
    whyItMatters: 'Near-nuclear threshold state; controls Strait of Hormuz; Axis of Resistance coordinator',
  },
  {
    id: 'telaviv',
    name: 'Tel Aviv',
    subtext: 'Mossad/IDF',
    lat: 32.1,
    lon: 34.8,
    location: 'Israel',
    keywords: ['israel', 'idf', 'mossad', 'gaza', 'netanyahu', 'israeli', 'hamas', 'hezbollah'],
    agencies: ['IDF', 'Mossad', 'Shin Bet'],
    description: 'Military operations. Regional security. Intelligence activities.',
    status: 'Monitoring',
    escalationScore: 5,
    escalationTrend: 'stable',
    escalationIndicators: ['Gaza operations ongoing', 'Hezbollah northern front', 'Iran shadow war', 'Judicial crisis paused'],
    history: {
      lastMajorEvent: 'October 7 attacks',
      lastMajorEventDate: '2023-10-07',
      precedentCount: 5,
      precedentDescription: '1948 War, 1967 Six-Day War, 1973 Yom Kippur, Lebanon 2006, Gaza wars',
      cyclicalRisk: 'Jewish holidays, Ramadan tensions, election cycles',
    },
    whyItMatters: 'Regional escalation risk to multi-front war; US treaty ally; Iran confrontation flashpoint',
  },
  {
    id: 'pyongyang',
    name: 'Pyongyang',
    subtext: 'DPRK Watch',
    lat: 39.0,
    lon: 125.75,
    location: 'North Korea',
    keywords: ['north korea', 'kim', 'pyongyang', 'dprk', 'korean'],
    agencies: ['KPA', 'RGB', 'Lazarus Group'],
    description: 'Nuclear weapons program. Missile testing. Cyber operations.',
    status: 'Monitoring',
    escalationScore: 3,
    escalationTrend: 'stable',
    escalationIndicators: ['ICBM testing resumed', 'Russia arms cooperation', 'Satellite launches', 'Constitution change on ROK'],
    history: {
      lastMajorEvent: 'Hwasong-18 ICBM test',
      lastMajorEventDate: '2023-12-18',
      precedentCount: 4,
      precedentDescription: 'Korean War 1950-53, nuclear tests 2006-2017, Trump summits, missile tests ongoing',
      cyclicalRisk: 'Kim Il-sung birthday (April 15), party anniversaries',
    },
    whyItMatters: 'Nuclear-armed hermit state; ICBM can reach US mainland; cyber threat actor; Russia military supplier',
  },
  {
    id: 'london',
    name: 'London',
    subtext: 'GCHQ/MI6',
    lat: 51.5,
    lon: -0.12,
    location: 'United Kingdom',
    keywords: ['london', 'uk', 'britain', 'gchq', 'mi6', 'british'],
    agencies: ['MI6', 'GCHQ', 'MI5'],
    description: 'UK intelligence headquarters. Five Eyes member.',
    status: 'Monitoring',
  },
  {
    id: 'brussels',
    name: 'Brussels',
    subtext: 'NATO HQ',
    lat: 50.85,
    lon: 4.35,
    location: 'Belgium (NATO HQ)',
    keywords: ['nato', 'brussels', 'eu', 'european union', 'europe'],
    agencies: ['NATO', 'EU Commission'],
    description: 'NATO alliance headquarters. European Union center.',
    status: 'Monitoring',
  },
  {
    id: 'caracas',
    name: 'Caracas',
    subtext: 'Venezuela Crisis',
    lat: 10.5,
    lon: -66.9,
    location: 'Venezuela',
    keywords: ['venezuela', 'maduro', 'caracas', 'venezuelan'],
    agencies: ['Maduro Govt', 'SEBIN'],
    description: 'Political crisis. Economic sanctions. Regional instability.',
    status: 'Monitoring',
  },
  {
    id: 'mexico',
    name: 'Mexico City',
    subtext: 'Cartel Violence',
    lat: 23.6,
    lon: -102.5,
    location: 'Mexico',
    keywords: ['mexico', 'cartel', 'sinaloa', 'jalisco', 'narco', 'cjng', 'fentanyl', 'el chapo', 'national guard mexico', 'zetas', 'michoacan', 'juarez', 'tijuana', 'border violence', 'mexican army', 'sedena', 'extradition mexico'],
    agencies: ['Sedena', 'National Guard', 'DEA', 'FGR'],
    description: 'Cartel warfare, fentanyl trafficking, military deployments, state fragility in multiple regions.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['Sinaloa cartel fragmentation', 'CJNG territorial expansion', 'Military deployed to multiple states', 'Record fentanyl seizures', 'Prison breaks and gang violence'],
    history: {
      lastMajorEvent: 'Sinaloa cartel leadership crisis',
      lastMajorEventDate: '2024-07-25',
      precedentCount: 5,
      precedentDescription: 'Decades of cartel wars (Sinaloa vs CJNG, Zetas era, Calderón drug war 2006, El Chapo captures)',
      cyclicalRisk: 'Election cycles trigger violence; cartel leadership changes spark turf wars',
    },
    whyItMatters: 'Largest US land border; fentanyl crisis killing 100k+ Americans/year; regional destabilization; migration driver',
  },
  {
    id: 'nuuk',
    name: 'Nuuk',
    subtext: 'Greenland Intel',
    lat: 64.18,
    lon: -51.7,
    location: 'Greenland (Denmark)',
    keywords: ['greenland', 'nuuk', 'arctic', 'denmark', 'danish'],
    agencies: ['Danish Defence', 'US Space Force', 'Arctic Council'],
    description: 'Arctic strategic territory. US military presence, sovereignty questions.',
    status: 'Monitoring',
  },
  // Middle East hotspots
  {
    id: 'riyadh',
    name: 'Riyadh',
    subtext: 'Saudi GIP/MBS',
    lat: 24.7,
    lon: 46.7,
    location: 'Saudi Arabia',
    keywords: ['saudi', 'riyadh', 'mbs', 'aramco', 'opec', 'saudi arabia'],
    agencies: ['GIP', 'Saudi Royal Court', 'Aramco'],
    description: 'Saudi Arabia power center. OPEC+ decisions. Regional influence.',
    status: 'Monitoring',
  },
  {
    id: 'cairo',
    name: 'Cairo',
    subtext: 'Egypt/GIS',
    lat: 30.0,
    lon: 31.2,
    location: 'Egypt',
    keywords: ['egypt', 'cairo', 'sisi', 'egyptian', 'suez'],
    agencies: ['GIS', 'Egyptian Armed Forces'],
    description: 'Egyptian command. Gaza border control. Suez Canal security.',
    status: 'Monitoring',
  },
  {
    id: 'baghdad',
    name: 'Baghdad',
    subtext: 'Iraq/PMF',
    lat: 33.3,
    lon: 44.4,
    location: 'Iraq',
    keywords: ['iraq', 'baghdad', 'iraqi', 'pmf', 'militia'],
    agencies: ['Iraqi Security Forces', 'PMF', 'US Embassy'],
    description: 'Iraqi government. Iran-backed militias. US military presence.',
    status: 'Monitoring',
  },
  {
    id: 'damascus',
    name: 'Damascus',
    subtext: 'Syria Crisis',
    lat: 33.5,
    lon: 36.3,
    location: 'Syria',
    keywords: ['syria', 'damascus', 'assad', 'syrian', 'hts'],
    agencies: ['Syrian Govt', 'HTS', 'Russian Forces', 'Turkish Forces'],
    description: 'Syrian civil war aftermath. Multiple foreign interventions.',
    status: 'Monitoring',
  },
  {
    id: 'doha',
    name: 'Doha',
    subtext: 'Qatar/Al Udeid',
    lat: 25.3,
    lon: 51.5,
    location: 'Qatar',
    keywords: ['qatar', 'doha', 'qatari', 'al jazeera'],
    agencies: ['Qatari State Security', 'CENTCOM Forward HQ'],
    description: 'Qatar diplomatic hub. US CENTCOM base. Al Jazeera HQ.',
    status: 'Monitoring',
  },
  {
    id: 'ankara',
    name: 'Ankara',
    subtext: 'Turkey/MIT',
    lat: 39.9,
    lon: 32.9,
    location: 'Turkey',
    keywords: ['turkey', 'ankara', 'erdogan', 'turkish', 'mit'],
    agencies: ['MIT', 'Turkish Armed Forces', 'AKP'],
    description: 'NATO member. Kurdish conflict. Syria/Libya operations.',
    status: 'Monitoring',
  },
  {
    id: 'beirut',
    name: 'Beirut',
    subtext: 'Lebanon/Hezbollah',
    lat: 33.9,
    lon: 35.5,
    location: 'Lebanon',
    keywords: ['lebanon', 'beirut', 'hezbollah', 'lebanese', 'nasrallah'],
    agencies: ['LAF', 'Hezbollah', 'UNIFIL'],
    description: 'Lebanon crisis. Hezbollah stronghold. Israel border tensions.',
    status: 'Monitoring',
  },
  {
    id: 'sanaa',
    name: "Sana'a",
    subtext: 'Yemen/Houthis',
    lat: 15.4,
    lon: 44.2,
    keywords: ['yemen', 'houthi', 'sanaa', 'yemeni', 'red sea'],
    agencies: ['Houthi Forces', 'Saudi Coalition', 'US Navy'],
    description: 'Yemen conflict. Houthi Red Sea attacks. Shipping disruption.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['Red Sea shipping attacks', 'US/UK strikes on Yemen', 'Iran weapon supplies', 'Commercial ship seizures'],
    history: {
      lastMajorEvent: 'Red Sea campaign begins',
      lastMajorEventDate: '2023-11-19',
      precedentCount: 3,
      precedentDescription: 'Civil war since 2014, Saudi intervention 2015, US strikes 2024',
      cyclicalRisk: 'Ramadan, Gaza war linkage',
    },
    whyItMatters: 'Disrupting 12% of global trade via Suez; insurance costs spiking; Iran proxy demonstration',
  },
  {
    id: 'abudhabi',
    name: 'Abu Dhabi',
    subtext: 'UAE/ECSR',
    lat: 24.5,
    lon: 54.4,
    keywords: ['uae', 'abu dhabi', 'emirates', 'emirati', 'dubai'],
    agencies: ['ECSR', 'UAE Armed Forces'],
    description: 'UAE strategic hub. Regional military operations.',
    status: 'Monitoring',
  },
];

// Strategic waterways layer has been removed - keeping empty export for backwards compatibility
export const STRATEGIC_WATERWAYS: StrategicWaterway[] = [];

export const APT_GROUPS: APTGroup[] = [
  { id: 'apt28', name: 'APT28/29', aka: 'Fancy Bear/Cozy Bear', sponsor: 'Russia (GRU/FSB)', lat: 55.0, lon: 40.0 },
  { id: 'apt41', name: 'APT41', aka: 'Double Dragon', sponsor: 'China (MSS)', lat: 38.0, lon: 118.0 },
  { id: 'lazarus', name: 'Lazarus', aka: 'Hidden Cobra', sponsor: 'North Korea (RGB)', lat: 38.5, lon: 127.0 },
  { id: 'apt33', name: 'APT33/35', aka: 'Elfin/Charming Kitten', sponsor: 'Iran (IRGC)', lat: 34.0, lon: 53.0 },
];

// Conflict zones layer has been removed - keeping empty export for backwards compatibility
export const CONFLICT_ZONES: ConflictZone[] = [];

// US Domestic bases (not in overseas dataset - these are CONUS bases)
export const US_DOMESTIC_BASES: MilitaryBase[] = [
  { id: 'norfolk', name: 'Norfolk Naval', lat: 36.95, lon: -76.31, type: 'us-nato', description: 'World largest naval base. Atlantic Fleet HQ.' },
  { id: 'fort_liberty', name: 'Fort Liberty', lat: 35.14, lon: -79.0, type: 'us-nato', description: 'Army Special Ops. XVIII Airborne Corps.' },
  { id: 'pendleton', name: 'Camp Pendleton', lat: 33.38, lon: -117.4, type: 'us-nato', description: 'USMC West Coast. 1st Marine Division.' },
  { id: 'san_diego', name: 'Naval San Diego', lat: 32.68, lon: -117.13, type: 'us-nato', description: 'Pacific Fleet. Carrier homeport.' },
  { id: 'nellis', name: 'Nellis AFB', lat: 36.24, lon: -115.03, type: 'us-nato', description: 'Air combat training. Red Flag exercises.' },
  { id: 'langley', name: 'Langley AFB', lat: 37.08, lon: -76.36, type: 'us-nato', description: 'Air Combat Command HQ. F-22 wing.' },
  { id: 'cheyenne', name: 'Cheyenne Mtn', lat: 38.74, lon: -104.85, type: 'us-nato', description: 'NORAD. Missile warning, space control.' },
  { id: 'peterson', name: 'Peterson SFB', lat: 38.82, lon: -104.71, type: 'us-nato', description: 'US Space Command HQ. Space operations.' },
  { id: 'kings_bay', name: 'Kings Bay', lat: 30.8, lon: -81.52, type: 'us-nato', description: 'Ohio-class submarine base. Atlantic deterrent.' },
  { id: 'kitsap', name: 'Naval Kitsap', lat: 47.56, lon: -122.66, type: 'us-nato', description: 'Trident submarine base. Pacific deterrent.' },
  { id: 'yokosuka', name: 'Yokosuka', lat: 35.28, lon: 139.67, type: 'us-nato', description: 'US 7th Fleet HQ. Carrier strike group homeport.' },
  { id: 'rota', name: 'Naval Rota', lat: 36.62, lon: -6.35, type: 'us-nato', description: 'US/Spanish naval base. Aegis destroyers, Atlantic access.' },
  { id: 'incirlik', name: 'Incirlik AB', lat: 37.0, lon: 35.43, type: 'us-nato', description: 'US/Turkish base. Nuclear weapons storage site.' },
  // Russian domestic bases (not overseas)
  { id: 'kaliningrad', name: 'Kaliningrad', lat: 54.71, lon: 20.51, type: 'russia', description: 'Russian exclave. Baltic Fleet, Iskander missiles.' },
  { id: 'sevastopol', name: 'Sevastopol', lat: 44.6, lon: 33.5, type: 'russia', description: 'Black Sea Fleet HQ. Crimea (occupied).' },
  { id: 'vladivostok', name: 'Vladivostok', lat: 43.12, lon: 131.9, type: 'russia', description: 'Pacific Fleet HQ. Nuclear submarines.' },
  { id: 'murmansk', name: 'Murmansk', lat: 68.97, lon: 33.09, type: 'russia', description: 'Northern Fleet. Strategic nuclear submarines.' },
];

// Military bases layer has been removed - keeping empty export for backwards compatibility
export const MILITARY_BASES: MilitaryBase[] = [];

export const UNDERSEA_CABLES: UnderseaCable[] = [
  // === TRANS-ATLANTIC (3 - south/central/north routes) ===
  {
    id: 'marea',
    name: 'MAREA',
    points: [[-73.0, 39.0], [-30.0, 42.0], [-9.0, 37.0]],
    major: true,
    capacityTbps: 200,
    rfsYear: 2017,
    owners: ['Microsoft', 'Meta', 'Telxius'],
    landingPoints: [
      { country: 'US', countryName: 'United States', city: 'Virginia Beach', lat: 36.85, lon: -75.98 },
      { country: 'ES', countryName: 'Spain', city: 'Bilbao', lat: 43.26, lon: -2.93 },
    ],
    countriesServed: [
      { country: 'US', capacityShare: 0.05, isRedundant: true },
      { country: 'ES', capacityShare: 0.15, isRedundant: true },
      { country: 'GB', capacityShare: 0.08, isRedundant: true },
      { country: 'FR', capacityShare: 0.06, isRedundant: true },
    ],
  },
  {
    id: 'grace_hopper',
    name: 'Grace Hopper',
    points: [[-74.0, 40.0], [-30.0, 44.0], [-6.0, 53.0], [-9.0, 37.0]],
    major: true,
    capacityTbps: 340,
    rfsYear: 2022,
    owners: ['Google'],
    landingPoints: [
      { country: 'US', countryName: 'United States', city: 'New York', lat: 40.57, lon: -73.97 },
      { country: 'GB', countryName: 'United Kingdom', city: 'Bude', lat: 50.83, lon: -4.55 },
      { country: 'ES', countryName: 'Spain', city: 'Bilbao', lat: 43.26, lon: -2.93 },
    ],
    countriesServed: [
      { country: 'US', capacityShare: 0.04, isRedundant: true },
      { country: 'GB', capacityShare: 0.12, isRedundant: true },
      { country: 'ES', capacityShare: 0.10, isRedundant: true },
    ],
  },
  {
    id: 'havfrue',
    name: 'Havfrue',
    points: [[-74.0, 40.5], [-30.0, 55.0], [5.0, 58.0], [12.0, 56.0]],
    major: true,
    capacityTbps: 108,
    rfsYear: 2020,
    owners: ['Google', 'Facebook', 'Aqua Comms'],
    landingPoints: [
      { country: 'US', countryName: 'United States', city: 'New Jersey', lat: 40.22, lon: -74.01 },
      { country: 'NO', countryName: 'Norway', city: 'Kristiansand', lat: 58.15, lon: 8.0 },
      { country: 'DK', countryName: 'Denmark', city: 'Blaabjerg', lat: 55.56, lon: 8.13 },
    ],
    countriesServed: [
      { country: 'US', capacityShare: 0.02, isRedundant: true },
      { country: 'NO', capacityShare: 0.25, isRedundant: true },
      { country: 'DK', capacityShare: 0.20, isRedundant: true },
    ],
  },

  // === TRANS-PACIFIC (3 - US-Asia, US-Australia, US-South America) ===
  {
    id: 'faster',
    name: 'FASTER',
    points: [[-122.0, 37.0], [-155.0, 22.0], [139.0, 35.0]],
    major: true,
    capacityTbps: 60,
    rfsYear: 2016,
    owners: ['Google', 'China Mobile', 'China Telecom', 'KDDI', 'SingTel'],
    landingPoints: [
      { country: 'US', countryName: 'United States', city: 'Oregon', lat: 43.37, lon: -124.22 },
      { country: 'JP', countryName: 'Japan', city: 'Chikura', lat: 34.95, lon: 139.95 },
      { country: 'JP', countryName: 'Japan', city: 'Shima', lat: 34.32, lon: 136.85 },
    ],
    countriesServed: [
      { country: 'US', capacityShare: 0.03, isRedundant: true },
      { country: 'JP', capacityShare: 0.15, isRedundant: true },
    ],
  },
  {
    id: 'southern_cross',
    name: 'Southern Cross',
    points: [[151.0, -34.0], [-175.0, -40.0], [-122.0, 34.0]],
    major: true,
    capacityTbps: 72,
    rfsYear: 2000,
    owners: ['Southern Cross Cables'],
    landingPoints: [
      { country: 'AU', countryName: 'Australia', city: 'Sydney', lat: -33.87, lon: 151.21 },
      { country: 'NZ', countryName: 'New Zealand', city: 'Auckland', lat: -36.85, lon: 174.76 },
      { country: 'US', countryName: 'United States', city: 'Los Angeles', lat: 33.74, lon: -118.27 },
    ],
    countriesServed: [
      { country: 'AU', capacityShare: 0.20, isRedundant: true },
      { country: 'NZ', capacityShare: 0.35, isRedundant: false },
      { country: 'FJ', capacityShare: 0.15, isRedundant: false },
    ],
  },
  {
    id: 'curie',
    name: 'Curie',
    points: [[-122.4, 37.8], [-90.0, 10.0], [-77.0, -12.0]],
    major: true,
    capacityTbps: 72,
    rfsYear: 2019,
    owners: ['Google'],
    landingPoints: [
      { country: 'US', countryName: 'United States', city: 'Los Angeles', lat: 33.74, lon: -118.27 },
      { country: 'CL', countryName: 'Chile', city: 'Valparaiso', lat: -33.05, lon: -71.62 },
    ],
    countriesServed: [
      { country: 'US', capacityShare: 0.01, isRedundant: true },
      { country: 'CL', capacityShare: 0.25, isRedundant: true },
      { country: 'PA', capacityShare: 0.10, isRedundant: true },
    ],
  },

  // === ASIA-EUROPE (2 - SEA-ME-WE corridor + alternative) ===
  {
    id: 'seamewe6',
    name: 'SEA-ME-WE 6',
    points: [[103.8, 1.3], [80.0, 6.0], [55.0, 24.0], [43.0, 12.0], [32.5, 30.0], [12.5, 42.0], [-9.0, 38.0]],
    major: true,
    capacityTbps: 100,
    rfsYear: 2025,
    owners: ['Consortium'],
    landingPoints: [
      { country: 'SG', countryName: 'Singapore', city: 'Singapore', lat: 1.35, lon: 103.82 },
      { country: 'IN', countryName: 'India', city: 'Mumbai', lat: 19.08, lon: 72.88 },
      { country: 'AE', countryName: 'UAE', city: 'Fujairah', lat: 25.13, lon: 56.34 },
      { country: 'SA', countryName: 'Saudi Arabia', city: 'Jeddah', lat: 21.49, lon: 39.19 },
      { country: 'EG', countryName: 'Egypt', city: 'Suez', lat: 29.97, lon: 32.55 },
      { country: 'FR', countryName: 'France', city: 'Marseille', lat: 43.30, lon: 5.37 },
    ],
    countriesServed: [
      { country: 'SG', capacityShare: 0.10, isRedundant: true },
      { country: 'IN', capacityShare: 0.15, isRedundant: true },
      { country: 'AE', capacityShare: 0.12, isRedundant: true },
      { country: 'SA', capacityShare: 0.08, isRedundant: true },
      { country: 'EG', capacityShare: 0.10, isRedundant: true },
    ],
  },
  {
    id: 'flag',
    name: 'FLAG Europe-Asia',
    points: [[0.0, 51.0], [-6.0, 36.0], [32.5, 30.0], [55.0, 24.0], [73.0, 15.0], [103.8, 1.3], [139.7, 35.7]],
    major: true,
    capacityTbps: 10,
    rfsYear: 1997,
    owners: ['Global Cloud Xchange'],
    landingPoints: [
      { country: 'GB', countryName: 'United Kingdom', city: 'Porthcurno', lat: 50.04, lon: -5.66 },
      { country: 'EG', countryName: 'Egypt', city: 'Alexandria', lat: 31.20, lon: 29.92 },
      { country: 'AE', countryName: 'UAE', city: 'Dubai', lat: 25.20, lon: 55.27 },
      { country: 'IN', countryName: 'India', city: 'Mumbai', lat: 19.08, lon: 72.88 },
      { country: 'SG', countryName: 'Singapore', city: 'Singapore', lat: 1.35, lon: 103.82 },
      { country: 'JP', countryName: 'Japan', city: 'Tokyo', lat: 35.69, lon: 139.69 },
    ],
    countriesServed: [
      { country: 'IN', capacityShare: 0.23, isRedundant: false },
      { country: 'AE', capacityShare: 0.18, isRedundant: true },
      { country: 'SA', capacityShare: 0.12, isRedundant: true },
      { country: 'EG', capacityShare: 0.09, isRedundant: true },
      { country: 'PK', capacityShare: 0.07, isRedundant: false },
    ],
  },

  // === AFRICA (3 - circumnavigation + west + east backbones) ===
  {
    id: '2africa',
    name: '2Africa',
    points: [[0.0, 51.0], [-9.0, 38.0], [-17.0, 15.0], [4.0, 6.0], [18.0, -34.0], [55.0, -20.0], [55.0, 24.0], [32.5, 30.0]],
    major: true,
    capacityTbps: 180,
    rfsYear: 2024,
    owners: ['Meta', 'MTN', 'Vodafone', 'Orange'],
    landingPoints: [
      { country: 'GB', countryName: 'United Kingdom', city: 'Bude', lat: 50.83, lon: -4.55 },
      { country: 'PT', countryName: 'Portugal', city: 'Lisbon', lat: 38.72, lon: -9.14 },
      { country: 'SN', countryName: 'Senegal', city: 'Dakar', lat: 14.69, lon: -17.44 },
      { country: 'NG', countryName: 'Nigeria', city: 'Lagos', lat: 6.52, lon: 3.38 },
      { country: 'ZA', countryName: 'South Africa', city: 'Cape Town', lat: -33.93, lon: 18.42 },
      { country: 'KE', countryName: 'Kenya', city: 'Mombasa', lat: -4.04, lon: 39.67 },
      { country: 'SA', countryName: 'Saudi Arabia', city: 'Jeddah', lat: 21.49, lon: 39.19 },
      { country: 'EG', countryName: 'Egypt', city: 'Port Said', lat: 31.26, lon: 32.30 },
    ],
    countriesServed: [
      { country: 'NG', capacityShare: 0.30, isRedundant: true },
      { country: 'ZA', capacityShare: 0.20, isRedundant: true },
      { country: 'KE', capacityShare: 0.25, isRedundant: true },
      { country: 'SN', capacityShare: 0.35, isRedundant: false },
      { country: 'EG', capacityShare: 0.08, isRedundant: true },
    ],
  },
  {
    id: 'wacs',
    name: 'WACS',
    points: [[18.0, -34.0], [12.0, -6.0], [4.0, 6.0], [-17.0, 15.0], [-6.0, 36.0], [0.0, 51.0]],
    major: true,
    capacityTbps: 14.5,
    rfsYear: 2012,
    owners: ['MTN', 'Vodacom', 'Togo Telecom'],
    landingPoints: [
      { country: 'ZA', countryName: 'South Africa', city: 'Cape Town', lat: -33.93, lon: 18.42 },
      { country: 'NG', countryName: 'Nigeria', city: 'Lagos', lat: 6.52, lon: 3.38 },
      { country: 'GB', countryName: 'United Kingdom', city: 'London', lat: 51.51, lon: -0.13 },
      { country: 'PT', countryName: 'Portugal', city: 'Lisbon', lat: 38.72, lon: -9.14 },
    ],
    countriesServed: [
      { country: 'ZA', capacityShare: 0.15, isRedundant: true },
      { country: 'NG', capacityShare: 0.20, isRedundant: true },
      { country: 'GH', capacityShare: 0.30, isRedundant: false },
      { country: 'CI', capacityShare: 0.35, isRedundant: false },
    ],
  },
  {
    id: 'eassy',
    name: 'EASSy',
    points: [[18.0, -34.0], [32.0, -26.0], [40.0, -15.0], [44.0, -12.0], [50.0, -20.0], [55.0, 24.0]],
    major: true,
    capacityTbps: 10,
    rfsYear: 2010,
    owners: ['Consortium of 16 telecom companies'],
    landingPoints: [
      { country: 'ZA', countryName: 'South Africa', city: 'Mtunzini', lat: -28.95, lon: 31.75 },
      { country: 'MZ', countryName: 'Mozambique', city: 'Maputo', lat: -25.97, lon: 32.58 },
      { country: 'TZ', countryName: 'Tanzania', city: 'Dar es Salaam', lat: -6.79, lon: 39.28 },
      { country: 'KE', countryName: 'Kenya', city: 'Mombasa', lat: -4.04, lon: 39.67 },
      { country: 'DJ', countryName: 'Djibouti', city: 'Djibouti', lat: 11.59, lon: 43.15 },
    ],
    countriesServed: [
      { country: 'KE', capacityShare: 0.20, isRedundant: true },
      { country: 'TZ', capacityShare: 0.30, isRedundant: false },
      { country: 'MZ', capacityShare: 0.25, isRedundant: false },
      { country: 'MG', capacityShare: 0.40, isRedundant: false },
    ],
  },

  // === AMERICAS (2 - South America backbone + Europe direct) ===
  {
    id: 'sam1',
    name: 'SAm-1',
    points: [[-43.0, -23.0], [-55.0, -35.0], [-70.0, -33.0], [-77.0, -12.0]],
    major: true,
    capacityTbps: 2,
    rfsYear: 2001,
    owners: ['Telxius'],
    landingPoints: [
      { country: 'BR', countryName: 'Brazil', city: 'Rio de Janeiro', lat: -22.91, lon: -43.17 },
      { country: 'AR', countryName: 'Argentina', city: 'Buenos Aires', lat: -34.60, lon: -58.38 },
      { country: 'CL', countryName: 'Chile', city: 'Valparaiso', lat: -33.05, lon: -71.62 },
      { country: 'PE', countryName: 'Peru', city: 'Lima', lat: -12.05, lon: -77.04 },
    ],
    countriesServed: [
      { country: 'BR', capacityShare: 0.05, isRedundant: true },
      { country: 'AR', capacityShare: 0.15, isRedundant: true },
      { country: 'CL', capacityShare: 0.10, isRedundant: true },
      { country: 'PE', capacityShare: 0.12, isRedundant: true },
    ],
  },
  {
    id: 'ellalink',
    name: 'EllaLink',
    points: [[-9.0, 38.0], [-25.0, 20.0], [-35.0, -5.0]],
    major: true,
    capacityTbps: 72,
    rfsYear: 2021,
    owners: ['EllaLink'],
    landingPoints: [
      { country: 'PT', countryName: 'Portugal', city: 'Sines', lat: 37.95, lon: -8.87 },
      { country: 'BR', countryName: 'Brazil', city: 'Fortaleza', lat: -3.73, lon: -38.53 },
    ],
    countriesServed: [
      { country: 'BR', capacityShare: 0.08, isRedundant: true },
      { country: 'PT', capacityShare: 0.15, isRedundant: true },
    ],
  },

  // === ASIA-PACIFIC (3 - regional backbone + Australia) ===
  {
    id: 'apg',
    name: 'APG',
    points: [[139.7, 35.7], [121.5, 25.0], [114.0, 22.3], [103.8, 1.3]],
    major: true,
    capacityTbps: 54,
    rfsYear: 2016,
    owners: ['NTT', 'China Telecom', 'PLDT', 'Viettel'],
    landingPoints: [
      { country: 'JP', countryName: 'Japan', city: 'Tokyo', lat: 35.69, lon: 139.69 },
      { country: 'TW', countryName: 'Taiwan', city: 'Taipei', lat: 25.03, lon: 121.57 },
      { country: 'HK', countryName: 'Hong Kong', city: 'Hong Kong', lat: 22.32, lon: 114.17 },
      { country: 'SG', countryName: 'Singapore', city: 'Singapore', lat: 1.35, lon: 103.82 },
      { country: 'VN', countryName: 'Vietnam', city: 'Da Nang', lat: 16.05, lon: 108.22 },
    ],
    countriesServed: [
      { country: 'JP', capacityShare: 0.08, isRedundant: true },
      { country: 'TW', capacityShare: 0.15, isRedundant: true },
      { country: 'VN', capacityShare: 0.25, isRedundant: true },
      { country: 'TH', capacityShare: 0.10, isRedundant: true },
    ],
  },
  {
    id: 'indigo',
    name: 'Indigo',
    points: [[103.8, 1.3], [115.0, -8.0], [151.0, -34.0]],
    major: true,
    capacityTbps: 36,
    rfsYear: 2019,
    owners: ['Google', 'AARNet', 'Indosat', 'Singtel', 'SubPartners'],
    landingPoints: [
      { country: 'SG', countryName: 'Singapore', city: 'Singapore', lat: 1.35, lon: 103.82 },
      { country: 'ID', countryName: 'Indonesia', city: 'Jakarta', lat: -6.21, lon: 106.85 },
      { country: 'AU', countryName: 'Australia', city: 'Sydney', lat: -33.87, lon: 151.21 },
    ],
    countriesServed: [
      { country: 'AU', capacityShare: 0.12, isRedundant: true },
      { country: 'ID', capacityShare: 0.15, isRedundant: true },
      { country: 'SG', capacityShare: 0.05, isRedundant: true },
    ],
  },
  {
    id: 'sjc',
    name: 'SJC',
    points: [[103.8, 1.3], [114.0, 22.3], [139.7, 35.7], [-122.0, 34.0]],
    major: true,
    capacityTbps: 28,
    rfsYear: 2013,
    owners: ['China Mobile', 'China Telecom', 'Google', 'KDDI'],
    landingPoints: [
      { country: 'SG', countryName: 'Singapore', city: 'Singapore', lat: 1.35, lon: 103.82 },
      { country: 'HK', countryName: 'Hong Kong', city: 'Hong Kong', lat: 22.32, lon: 114.17 },
      { country: 'JP', countryName: 'Japan', city: 'Chikura', lat: 34.95, lon: 139.95 },
      { country: 'US', countryName: 'United States', city: 'Los Angeles', lat: 33.74, lon: -118.27 },
    ],
    countriesServed: [
      { country: 'US', capacityShare: 0.02, isRedundant: true },
      { country: 'JP', capacityShare: 0.10, isRedundant: true },
      { country: 'CN', capacityShare: 0.05, isRedundant: true },
      { country: 'SG', capacityShare: 0.08, isRedundant: true },
    ],
  },

  // === ARCTIC/EUROPE (1 - Iceland connectivity) ===
  {
    id: 'farice',
    name: 'FARICE',
    points: [[-22.0, 64.0], [-7.0, 62.0], [-6.0, 53.0]],
    major: true,
    capacityTbps: 5,
    rfsYear: 2004,
    owners: ['Farice ehf'],
    landingPoints: [
      { country: 'IS', countryName: 'Iceland', city: 'Reykjavik', lat: 64.13, lon: -21.90 },
      { country: 'FO', countryName: 'Faroe Islands', city: 'Torshavn', lat: 62.01, lon: -6.77 },
      { country: 'GB', countryName: 'United Kingdom', city: 'Edinburgh', lat: 55.95, lon: -3.19 },
    ],
    countriesServed: [
      { country: 'IS', capacityShare: 0.60, isRedundant: false },
      { country: 'FO', capacityShare: 0.70, isRedundant: false },
    ],
  },

  // === MIDDLE EAST (1 - Gulf region) ===
  {
    id: 'falcon',
    name: 'Falcon',
    points: [[55.0, 24.0], [56.0, 25.0], [51.5, 26.0], [48.0, 29.0]],
    major: true,
    capacityTbps: 5,
    rfsYear: 2006,
    owners: ['GBI'],
    landingPoints: [
      { country: 'AE', countryName: 'UAE', city: 'Fujairah', lat: 25.13, lon: 56.34 },
      { country: 'OM', countryName: 'Oman', city: 'Muscat', lat: 23.59, lon: 58.38 },
      { country: 'BH', countryName: 'Bahrain', city: 'Manama', lat: 26.23, lon: 50.59 },
      { country: 'KW', countryName: 'Kuwait', city: 'Kuwait City', lat: 29.38, lon: 47.98 },
    ],
    countriesServed: [
      { country: 'AE', capacityShare: 0.08, isRedundant: true },
      { country: 'OM', capacityShare: 0.15, isRedundant: true },
      { country: 'BH', capacityShare: 0.20, isRedundant: true },
      { country: 'KW', capacityShare: 0.15, isRedundant: true },
    ],
  },
];

// NUCLEAR_FACILITIES: layer removed - empty export kept for backwards compatibility
export const NUCLEAR_FACILITIES: NuclearFacility[] = [];

export const SANCTIONED_COUNTRIES: Record<number, 'severe' | 'high' | 'moderate'> = {
  408: 'severe',   // North Korea
  728: 'severe',   // South Sudan
  760: 'severe',   // Syria
  364: 'high',     // Iran
  643: 'high',     // Russia
  112: 'high',     // Belarus
  862: 'moderate', // Venezuela
  104: 'moderate', // Myanmar
  178: 'moderate', // Congo
};

export const MAP_URLS = {
  world: 'https://cdn.jsdelivr.net/npm/world-atlas@2/countries-50m.json',
  us: 'https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json',
};

// Global Economic Centers - Stock Exchanges, Central Banks, Financial Hubs
export const ECONOMIC_CENTERS: EconomicCenter[] = [
  // Americas
  { id: 'nyse', name: 'NYSE', type: 'exchange', lat: 40.7069, lon: -74.0089, country: 'USA', marketHours: { open: '09:30', close: '16:00', timezone: 'America/New_York' }, description: 'New York Stock Exchange - World\'s largest stock exchange' },
  { id: 'nasdaq', name: 'NASDAQ', type: 'exchange', lat: 40.7569, lon: -73.9896, country: 'USA', marketHours: { open: '09:30', close: '16:00', timezone: 'America/New_York' }, description: 'Tech-heavy exchange' },
  { id: 'fed', name: 'Federal Reserve', type: 'central-bank', lat: 38.8927, lon: -77.0459, country: 'USA', description: 'US Central Bank - Controls USD monetary policy' },
  { id: 'cme', name: 'CME Group', type: 'exchange', lat: 41.8819, lon: -87.6278, country: 'USA', description: 'Chicago Mercantile Exchange - Futures & derivatives' },
  { id: 'tsx', name: 'TSX', type: 'exchange', lat: 43.6489, lon: -79.3850, country: 'Canada', marketHours: { open: '09:30', close: '16:00', timezone: 'America/Toronto' }, description: 'Toronto Stock Exchange' },
  { id: 'bovespa', name: 'B3', type: 'exchange', lat: -23.5505, lon: -46.6333, country: 'Brazil', description: 'Brazilian Stock Exchange (B3/Bovespa)' },
  // Europe
  { id: 'lse', name: 'LSE', type: 'exchange', lat: 51.5145, lon: -0.0940, country: 'UK', marketHours: { open: '08:00', close: '16:30', timezone: 'Europe/London' }, description: 'London Stock Exchange' },
  { id: 'boe', name: 'Bank of England', type: 'central-bank', lat: 51.5142, lon: -0.0880, country: 'UK', description: 'UK Central Bank' },
  { id: 'ecb', name: 'ECB', type: 'central-bank', lat: 50.1096, lon: 8.6732, country: 'Germany', description: 'European Central Bank - Controls EUR' },
  { id: 'euronext', name: 'Euronext', type: 'exchange', lat: 48.8690, lon: 2.3364, country: 'France', marketHours: { open: '09:00', close: '17:30', timezone: 'Europe/Paris' }, description: 'Pan-European Exchange (Paris, Amsterdam, Brussels, Lisbon)' },
  { id: 'dax', name: 'Deutsche Börse', type: 'exchange', lat: 50.1109, lon: 8.6821, country: 'Germany', marketHours: { open: '09:00', close: '17:30', timezone: 'Europe/Berlin' }, description: 'Frankfurt Stock Exchange - DAX' },
  { id: 'six', name: 'SIX Swiss', type: 'exchange', lat: 47.3769, lon: 8.5417, country: 'Switzerland', description: 'Swiss Exchange' },
  { id: 'snb', name: 'SNB', type: 'central-bank', lat: 46.9480, lon: 7.4474, country: 'Switzerland', description: 'Swiss National Bank' },
  // Asia-Pacific
  { id: 'tse', name: 'Tokyo SE', type: 'exchange', lat: 35.6830, lon: 139.7744, country: 'Japan', marketHours: { open: '09:00', close: '15:00', timezone: 'Asia/Tokyo' }, description: 'Tokyo Stock Exchange - Nikkei' },
  { id: 'boj', name: 'Bank of Japan', type: 'central-bank', lat: 35.6855, lon: 139.7579, country: 'Japan', description: 'Japan Central Bank - Controls JPY' },
  { id: 'sse', name: 'Shanghai SE', type: 'exchange', lat: 31.2304, lon: 121.4737, country: 'China', marketHours: { open: '09:30', close: '15:00', timezone: 'Asia/Shanghai' }, description: 'Shanghai Stock Exchange' },
  { id: 'szse', name: 'Shenzhen SE', type: 'exchange', lat: 22.5431, lon: 114.0579, country: 'China', description: 'Shenzhen Stock Exchange - Tech focus' },
  { id: 'pboc', name: 'PBOC', type: 'central-bank', lat: 39.9208, lon: 116.4074, country: 'China', description: 'People\'s Bank of China - Controls CNY' },
  { id: 'hkex', name: 'HKEX', type: 'exchange', lat: 22.2833, lon: 114.1577, country: 'Hong Kong', marketHours: { open: '09:30', close: '16:00', timezone: 'Asia/Hong_Kong' }, description: 'Hong Kong Exchange' },
  { id: 'sgx', name: 'SGX', type: 'exchange', lat: 1.2834, lon: 103.8607, country: 'Singapore', description: 'Singapore Exchange' },
  { id: 'mas', name: 'MAS', type: 'central-bank', lat: 1.2789, lon: 103.8536, country: 'Singapore', description: 'Monetary Authority of Singapore' },
  { id: 'kospi', name: 'KRX', type: 'exchange', lat: 37.5665, lon: 126.9780, country: 'South Korea', marketHours: { open: '09:00', close: '15:30', timezone: 'Asia/Seoul' }, description: 'Korea Exchange - KOSPI' },
  { id: 'bse', name: 'BSE', type: 'exchange', lat: 18.9307, lon: 72.8335, country: 'India', marketHours: { open: '09:15', close: '15:30', timezone: 'Asia/Kolkata' }, description: 'Bombay Stock Exchange - Sensex' },
  { id: 'nse', name: 'NSE India', type: 'exchange', lat: 19.0571, lon: 72.8621, country: 'India', description: 'National Stock Exchange - Nifty' },
  { id: 'rbi', name: 'RBI', type: 'central-bank', lat: 18.9322, lon: 72.8351, country: 'India', description: 'Reserve Bank of India' },
  { id: 'asx', name: 'ASX', type: 'exchange', lat: -33.8688, lon: 151.2093, country: 'Australia', marketHours: { open: '10:00', close: '16:00', timezone: 'Australia/Sydney' }, description: 'Australian Securities Exchange' },
  { id: 'rba', name: 'RBA', type: 'central-bank', lat: -33.8654, lon: 151.2105, country: 'Australia', description: 'Reserve Bank of Australia' },
  // Middle East & Africa
  { id: 'tadawul', name: 'Tadawul', type: 'exchange', lat: 24.6877, lon: 46.7219, country: 'Saudi Arabia', marketHours: { open: '10:00', close: '15:00', timezone: 'Asia/Riyadh' }, description: 'Saudi Stock Exchange - Largest in Arab world' },
  { id: 'adx', name: 'ADX', type: 'exchange', lat: 24.4539, lon: 54.3773, country: 'UAE', marketHours: { open: '10:00', close: '14:00', timezone: 'Asia/Dubai' }, description: 'Abu Dhabi Securities Exchange' },
  { id: 'dfm', name: 'DFM', type: 'exchange', lat: 25.2221, lon: 55.2867, country: 'UAE', marketHours: { open: '10:00', close: '14:00', timezone: 'Asia/Dubai' }, description: 'Dubai Financial Market' },
  { id: 'qse', name: 'QSE', type: 'exchange', lat: 25.2854, lon: 51.5310, country: 'Qatar', marketHours: { open: '09:30', close: '13:15', timezone: 'Asia/Qatar' }, description: 'Qatar Stock Exchange' },
  { id: 'bkw', name: 'Boursa Kuwait', type: 'exchange', lat: 29.3759, lon: 47.9774, country: 'Kuwait', marketHours: { open: '09:00', close: '12:30', timezone: 'Asia/Kuwait' }, description: 'Kuwait Stock Exchange' },
  { id: 'bse_bahrain', name: 'Bahrain Bourse', type: 'exchange', lat: 26.2285, lon: 50.5860, country: 'Bahrain', description: 'Bahrain Stock Exchange' },
  { id: 'egx', name: 'EGX', type: 'exchange', lat: 30.0444, lon: 31.2357, country: 'Egypt', marketHours: { open: '10:00', close: '14:30', timezone: 'Africa/Cairo' }, description: 'Egyptian Exchange - Cairo' },
  { id: 'tase', name: 'TASE', type: 'exchange', lat: 32.0853, lon: 34.7818, country: 'Israel', marketHours: { open: '09:59', close: '17:14', timezone: 'Asia/Jerusalem' }, description: 'Tel Aviv Stock Exchange' },
  { id: 'jse', name: 'JSE', type: 'exchange', lat: -26.1447, lon: 28.0381, country: 'South Africa', marketHours: { open: '09:00', close: '17:00', timezone: 'Africa/Johannesburg' }, description: 'Johannesburg Stock Exchange' },
  { id: 'nse_nigeria', name: 'NGX', type: 'exchange', lat: 6.4541, lon: 3.4218, country: 'Nigeria', description: 'Nigerian Exchange Group - Lagos' },
  { id: 'casa', name: 'Casablanca SE', type: 'exchange', lat: 33.5731, lon: -7.5898, country: 'Morocco', description: 'Casablanca Stock Exchange' },
  // Financial Hubs (not exchanges but major centers)
  { id: 'dubai_hub', name: 'DIFC', type: 'financial-hub', lat: 25.2116, lon: 55.2708, country: 'UAE', description: 'Dubai International Financial Centre' },
  { id: 'cayman', name: 'Cayman Islands', type: 'financial-hub', lat: 19.3133, lon: -81.2546, country: 'Cayman Islands', description: 'Offshore financial center' },
  { id: 'luxembourg', name: 'Luxembourg', type: 'financial-hub', lat: 49.6116, lon: 6.1319, country: 'Luxembourg', description: 'European investment fund center' },
];

export const SPACEPORTS: Spaceport[] = [
  { id: 'ksc', name: 'Kennedy Space Center', lat: 28.57, lon: -80.64, country: 'USA', operator: 'NASA/Space Force', status: 'active', launches: 'High' },
  { id: 'vandenberg', name: 'Vandenberg SFB', lat: 34.74, lon: -120.57, country: 'USA', operator: 'US Space Force', status: 'active', launches: 'Medium' },
  { id: 'boca_chica', name: 'Starbase', lat: 25.99, lon: -97.15, country: 'USA', operator: 'SpaceX', status: 'active', launches: 'High' },
  { id: 'baikonur', name: 'Baikonur Cosmodrome', lat: 45.96, lon: 63.30, country: 'Kazakhstan', operator: 'Roscosmos', status: 'active', launches: 'Medium' },
  { id: 'plesetsk', name: 'Plesetsk Cosmodrome', lat: 62.92, lon: 40.57, country: 'Russia', operator: 'Roscosmos/Military', status: 'active', launches: 'Medium' },
  { id: 'vostochny', name: 'Vostochny Cosmodrome', lat: 51.88, lon: 128.33, country: 'Russia', operator: 'Roscosmos', status: 'active', launches: 'Low' },
  { id: 'jiuquan', name: 'Jiuquan SLC', lat: 40.96, lon: 100.29, country: 'China', operator: 'CNSA', status: 'active', launches: 'High' },
  { id: 'xichang', name: 'Xichang SLC', lat: 28.24, lon: 102.02, country: 'China', operator: 'CNSA', status: 'active', launches: 'High' },
  { id: 'wenchang', name: 'Wenchang SLC', lat: 19.61, lon: 110.95, country: 'China', operator: 'CNSA', status: 'active', launches: 'Medium' },
  { id: 'kourou', name: 'Guiana Space Centre', lat: 5.23, lon: -52.76, country: 'France', operator: 'ESA/CNES', status: 'active', launches: 'Medium' },
  { id: 'sriharikota', name: 'Satish Dhawan SC', lat: 13.72, lon: 80.23, country: 'India', operator: 'ISRO', status: 'active', launches: 'Medium' },
  { id: 'tanegashima', name: 'Tanegashima SC', lat: 30.40, lon: 130.97, country: 'Japan', operator: 'JAXA', status: 'active', launches: 'Low' },
];

export const CRITICAL_MINERALS: CriticalMineralProject[] = [
  // Lithium
  { id: 'greenbushes', name: 'Greenbushes', lat: -33.86, lon: 116.01, mineral: 'Lithium', country: 'Australia', operator: 'Talison Lithium', status: 'producing', significance: 'Largest hard-rock lithium mine' },
  { id: 'atacama', name: 'Salar de Atacama', lat: -23.50, lon: -68.33, mineral: 'Lithium', country: 'Chile', operator: 'SQM/Albemarle', status: 'producing', significance: 'Largest brine lithium source' },
  { id: 'pilgangoora', name: 'Pilgangoora', lat: -21.03, lon: 118.91, mineral: 'Lithium', country: 'Australia', operator: 'Pilbara Minerals', status: 'producing', significance: 'Major hard-rock deposit' },
  { id: 'silver_peak', name: 'Silver Peak', lat: 37.75, lon: -117.65, country: 'USA', mineral: 'Lithium', operator: 'Albemarle', status: 'producing', significance: 'Only active US lithium mine' },
  // Cobalt
  { id: 'mutanda', name: 'Mutanda', lat: -10.78, lon: 25.80, mineral: 'Cobalt', country: 'DRC', operator: 'Glencore', status: 'producing', significance: 'World largest cobalt mine' },
  { id: 'tenke', name: 'Tenke Fungurume', lat: -10.61, lon: 26.16, mineral: 'Cobalt', country: 'DRC', operator: 'CMOC', status: 'producing', significance: 'Major Chinese-owned cobalt source' },
  // Rare Earths
  { id: 'bayan_obo', name: 'Bayan Obo', lat: 41.76, lon: 109.95, mineral: 'Rare Earths', country: 'China', operator: 'China Northern Rare Earth', status: 'producing', significance: 'World largest REE mine (45% global production)' },
  { id: 'mountain_pass', name: 'Mountain Pass', lat: 35.47, lon: -115.53, mineral: 'Rare Earths', country: 'USA', operator: 'MP Materials', status: 'producing', significance: 'Only major US REE mine' },
  { id: 'mount_weld', name: 'Mount Weld', lat: -28.86, lon: 122.17, mineral: 'Rare Earths', country: 'Australia', operator: 'Lynas', status: 'producing', significance: 'Major non-Chinese REE source' },
  // Nickel
  { id: 'wedabay', name: 'Weda Bay', lat: 0.47, lon: 127.94, mineral: 'Nickel', country: 'Indonesia', operator: 'Tsingshan/Eramet', status: 'producing', significance: 'Massive nickel pig iron production' },
  { id: 'norilsk', name: 'Norilsk', lat: 69.33, lon: 88.21, mineral: 'Nickel', country: 'Russia', operator: 'Nornickel', status: 'producing', significance: 'Major palladium/nickel source' },
];
